import SearchAnime from '@/components/search-anime'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ChackraProv from './chackraProv'
import { Box, Container } from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Anime List with Next.js 13',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ChackraProv>
                    <SearchAnime />
                    {children}
                </ChackraProv>
            </body>
        </html>
    )
}
